from enum import Enum


class IssueStatus(str, Enum):
    PENDING = "ISSUE_STATUS/PENDING"
    PAYMENT_READY = "ISSUE_STATUS/PAYMENT_READY"
    ISSUED = "ISSUE_STATUS/ISSUED"
    REJECTED = "ISSUE_STATUS/REJECTED"
    SHARED = "ISSUE_STATUS/SHARED"
    COMPLETED = "ISSUE_STATUS/COMPLETED"

